<?php

namespace Database\Seeders;

use App\Models\Service;
use Illuminate\Database\Seeder;

class ServiceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $services = [
            // Consultation Services
            [
                'name' => 'General Consultation',
                'description' => 'Comprehensive health examination and consultation',
                'category' => 'consultation',
                'base_price' => 75.00,
                'is_variable_pricing' => false,
                'estimated_duration' => 30,
                'service_code' => 'CON-GEN-001',
                'is_active' => true,
                'requires_appointment' => true,
            ],
            [
                'name' => 'Emergency Consultation',
                'description' => 'Urgent medical consultation for emergency cases',
                'category' => 'consultation',
                'base_price' => 150.00,
                'is_variable_pricing' => false,
                'estimated_duration' => 45,
                'service_code' => 'CON-EME-001',
                'is_active' => true,
                'requires_appointment' => false,
            ],
            [
                'name' => 'Follow-up Consultation',
                'description' => 'Follow-up examination for ongoing treatment',
                'category' => 'consultation',
                'base_price' => 50.00,
                'is_variable_pricing' => false,
                'estimated_duration' => 20,
                'service_code' => 'CON-FOL-001',
                'is_active' => true,
                'requires_appointment' => true,
            ],
            [
                'name' => 'Specialist Consultation',
                'description' => 'Consultation with veterinary specialist',
                'category' => 'consultation',
                'base_price' => 125.00,
                'is_variable_pricing' => false,
                'estimated_duration' => 45,
                'service_code' => 'CON-SPE-001',
                'is_active' => true,
                'requires_appointment' => true,
            ],

            // Diagnostic Services
            [
                'name' => 'X-Ray Examination',
                'description' => 'Digital radiographic examination',
                'category' => 'diagnostic',
                'base_price' => 120.00,
                'is_variable_pricing' => false,
                'estimated_duration' => 30,
                'service_code' => 'DIA-XRA-001',
                'is_active' => true,
                'requires_appointment' => true,
                'required_equipment' => ['X-ray machine', 'positioning aids'],
            ],
            [
                'name' => 'Blood Chemistry Panel',
                'description' => 'Comprehensive blood chemistry analysis',
                'category' => 'diagnostic',
                'base_price' => 85.00,
                'is_variable_pricing' => false,
                'estimated_duration' => 15,
                'service_code' => 'DIA-BLO-001',
                'is_active' => true,
                'requires_appointment' => false,
            ],
            [
                'name' => 'Complete Blood Count',
                'description' => 'Full blood cell count and analysis',
                'category' => 'diagnostic',
                'base_price' => 65.00,
                'is_variable_pricing' => false,
                'estimated_duration' => 15,
                'service_code' => 'DIA-CBC-001',
                'is_active' => true,
                'requires_appointment' => false,
            ],
            [
                'name' => 'Urinalysis',
                'description' => 'Complete urine analysis',
                'category' => 'diagnostic',
                'base_price' => 45.00,
                'is_variable_pricing' => false,
                'estimated_duration' => 10,
                'service_code' => 'DIA-URI-001',
                'is_active' => true,
                'requires_appointment' => false,
            ],
            [
                'name' => 'Fecal Examination',
                'description' => 'Microscopic examination of fecal sample',
                'category' => 'diagnostic',
                'base_price' => 35.00,
                'is_variable_pricing' => false,
                'estimated_duration' => 10,
                'service_code' => 'DIA-FEC-001',
                'is_active' => true,
                'requires_appointment' => false,
            ],
            [
                'name' => 'Ultrasound Examination',
                'description' => 'Abdominal or cardiac ultrasound',
                'category' => 'diagnostic',
                'base_price' => 200.00,
                'is_variable_pricing' => false,
                'estimated_duration' => 45,
                'service_code' => 'DIA-ULT-001',
                'is_active' => true,
                'requires_appointment' => true,
                'required_equipment' => ['Ultrasound machine'],
            ],

            // Treatment Services
            [
                'name' => 'Wound Treatment',
                'description' => 'Cleaning and treatment of wounds',
                'category' => 'treatment',
                'base_price' => 95.00,
                'is_variable_pricing' => true,
                'min_price' => 50.00,
                'max_price' => 200.00,
                'estimated_duration' => 30,
                'service_code' => 'TRE-WOU-001',
                'is_active' => true,
                'requires_appointment' => true,
            ],
            [
                'name' => 'Ear Cleaning',
                'description' => 'Professional ear cleaning and treatment',
                'category' => 'treatment',
                'base_price' => 40.00,
                'is_variable_pricing' => false,
                'estimated_duration' => 15,
                'service_code' => 'TRE-EAR-001',
                'is_active' => true,
                'requires_appointment' => false,
            ],
            [
                'name' => 'Nail Trimming',
                'description' => 'Professional nail trimming service',
                'category' => 'treatment',
                'base_price' => 25.00,
                'is_variable_pricing' => false,
                'estimated_duration' => 10,
                'service_code' => 'TRE-NAI-001',
                'is_active' => true,
                'requires_appointment' => false,
            ],
            [
                'name' => 'Dental Cleaning',
                'description' => 'Professional dental cleaning under anesthesia',
                'category' => 'treatment',
                'base_price' => 350.00,
                'is_variable_pricing' => true,
                'min_price' => 300.00,
                'max_price' => 500.00,
                'estimated_duration' => 120,
                'service_code' => 'TRE-DEN-001',
                'is_active' => true,
                'requires_appointment' => true,
                'required_equipment' => ['Dental equipment', 'anesthesia machine'],
            ],
            [
                'name' => 'Bandage Change',
                'description' => 'Changing and maintenance of bandages',
                'category' => 'treatment',
                'base_price' => 30.00,
                'is_variable_pricing' => false,
                'estimated_duration' => 15,
                'service_code' => 'TRE-BAN-001',
                'is_active' => true,
                'requires_appointment' => false,
            ],

            // Surgery Services
            [
                'name' => 'Spay Surgery',
                'description' => 'Ovariohysterectomy (female sterilization)',
                'category' => 'surgery',
                'base_price' => 450.00,
                'is_variable_pricing' => true,
                'min_price' => 400.00,
                'max_price' => 600.00,
                'estimated_duration' => 90,
                'service_code' => 'SUR-SPA-001',
                'is_active' => true,
                'requires_appointment' => true,
                'required_equipment' => ['Surgical suite', 'anesthesia machine'],
            ],
            [
                'name' => 'Neuter Surgery',
                'description' => 'Castration (male sterilization)',
                'category' => 'surgery',
                'base_price' => 350.00,
                'is_variable_pricing' => true,
                'min_price' => 300.00,
                'max_price' => 450.00,
                'estimated_duration' => 60,
                'service_code' => 'SUR-NEU-001',
                'is_active' => true,
                'requires_appointment' => true,
                'required_equipment' => ['Surgical suite', 'anesthesia machine'],
            ],
            [
                'name' => 'Tumor Removal',
                'description' => 'Surgical removal of tumors or masses',
                'category' => 'surgery',
                'base_price' => 800.00,
                'is_variable_pricing' => true,
                'min_price' => 500.00,
                'max_price' => 1500.00,
                'estimated_duration' => 120,
                'service_code' => 'SUR-TUM-001',
                'is_active' => true,
                'requires_appointment' => true,
                'required_equipment' => ['Surgical suite', 'anesthesia machine'],
            ],
            [
                'name' => 'Dental Extraction',
                'description' => 'Surgical extraction of damaged teeth',
                'category' => 'surgery',
                'base_price' => 250.00,
                'is_variable_pricing' => true,
                'min_price' => 150.00,
                'max_price' => 400.00,
                'estimated_duration' => 60,
                'service_code' => 'SUR-DEN-001',
                'is_active' => true,
                'requires_appointment' => true,
                'required_equipment' => ['Dental surgery equipment', 'anesthesia machine'],
            ],
            [
                'name' => 'Fracture Repair',
                'description' => 'Surgical repair of bone fractures',
                'category' => 'surgery',
                'base_price' => 1200.00,
                'is_variable_pricing' => true,
                'min_price' => 800.00,
                'max_price' => 2000.00,
                'estimated_duration' => 180,
                'service_code' => 'SUR-FRA-001',
                'is_active' => true,
                'requires_appointment' => true,
                'required_equipment' => ['Orthopedic surgical equipment', 'anesthesia machine'],
            ],

            // Vaccination Services
            [
                'name' => 'DHPP Vaccination',
                'description' => 'Distemper, Hepatitis, Parvovirus, Parainfluenza vaccine',
                'category' => 'vaccination',
                'base_price' => 45.00,
                'is_variable_pricing' => false,
                'estimated_duration' => 10,
                'service_code' => 'VAC-DHP-001',
                'is_active' => true,
                'requires_appointment' => false,
            ],
            [
                'name' => 'Rabies Vaccination',
                'description' => 'Rabies virus vaccination',
                'category' => 'vaccination',
                'base_price' => 35.00,
                'is_variable_pricing' => false,
                'estimated_duration' => 10,
                'service_code' => 'VAC-RAB-001',
                'is_active' => true,
                'requires_appointment' => false,
            ],
            [
                'name' => 'Bordetella Vaccination',
                'description' => 'Kennel cough vaccination',
                'category' => 'vaccination',
                'base_price' => 40.00,
                'is_variable_pricing' => false,
                'estimated_duration' => 10,
                'service_code' => 'VAC-BOR-001',
                'is_active' => true,
                'requires_appointment' => false,
            ],
            [
                'name' => 'Feline Distemper',
                'description' => 'Feline viral rhinotracheitis, calicivirus, panleukopenia vaccine',
                'category' => 'vaccination',
                'base_price' => 50.00,
                'is_variable_pricing' => false,
                'estimated_duration' => 10,
                'service_code' => 'VAC-FEL-001',
                'is_active' => true,
                'requires_appointment' => false,
            ],
            [
                'name' => 'Lyme Disease Vaccination',
                'description' => 'Lyme disease prevention vaccination',
                'category' => 'vaccination',
                'base_price' => 55.00,
                'is_variable_pricing' => false,
                'estimated_duration' => 10,
                'service_code' => 'VAC-LYM-001',
                'is_active' => true,
                'requires_appointment' => false,
            ],

            // Grooming Services
            [
                'name' => 'Basic Grooming',
                'description' => 'Bath, brush, nail trim, ear cleaning',
                'category' => 'grooming',
                'base_price' => 60.00,
                'is_variable_pricing' => true,
                'min_price' => 45.00,
                'max_price' => 85.00,
                'estimated_duration' => 60,
                'service_code' => 'GRO-BAS-001',
                'is_active' => true,
                'requires_appointment' => true,
            ],
            [
                'name' => 'Full Grooming',
                'description' => 'Complete grooming service with styling',
                'category' => 'grooming',
                'base_price' => 95.00,
                'is_variable_pricing' => true,
                'min_price' => 75.00,
                'max_price' => 125.00,
                'estimated_duration' => 90,
                'service_code' => 'GRO-FUL-001',
                'is_active' => true,
                'requires_appointment' => true,
            ],
            [
                'name' => 'Bath Only',
                'description' => 'Basic bathing service',
                'category' => 'grooming',
                'base_price' => 35.00,
                'is_variable_pricing' => false,
                'estimated_duration' => 30,
                'service_code' => 'GRO-BAT-001',
                'is_active' => true,
                'requires_appointment' => true,
            ],
        ];

        foreach ($services as $serviceData) {
            Service::create($serviceData);
        }

        // Create some additional random services using factory
        Service::factory(10)->create();
    }
} 